### pandas: Детали (Часть 2) [Домашнее задание]
> **Вы должны импортировать все необходимые пакеты самостоятельно.**

> **Пишите код только там, где это показано для записи. Не удаляйте комментарии!**

### Шаг 1

Пожалуйста, напишите функцию ```load_data(filename)```, которая будет загружать данные из csv-файла в список списков. Пожалуйста, напишите функцию ```load_data(filename)```, которая будет загружать данные из csv-файла в ```DataFrame```. Файл ```clean_house_prices.csv``` предоставлен вместе с этим jupyter notebook.


**Примечание:**

* В случае, если имя файла задано неверно, функция ```load_data``` должна вывести следующее сообщение об ошибке:

```{имя файла} does not exist```
* ```clean_house_prices.csv``` - это csv-файл, который является результатом вашей предыдущей домашней работы.

In [24]:
#Начало вашего кода
import os
import pandas as pd

def load_data(filename):
  if os.path.isfile(filename):
    with open(filename) as file:
      data = pd.read_csv(file)
      return data
  else:
    print('{} does not exist'.format(filename))
#Конец вашего кода

In [25]:
filename = "./SocialNetworkAds.csv"
data = load_data(filename=filename)

./SocialNetworkAds.csv does not exist

### Ожидаемый результат:

```
./SocialNetworkAds.csv does not exist
```

In [26]:
print(data)

None

### Ожидаемый результат:

```
None
```

In [27]:
filename = "./clean_house_prices.csv"
data = load_data(filename=filename)

In [28]:
print(data.columns.values)

['Id' 'MSSubClass' 'MSZoning' 'LotArea' 'Street' 'LotShape' 'LandContour'
 'Utilities' 'LotConfig' 'LandSlope' 'Neighborhood' 'Condition1'
 'Condition2' 'BldgType' 'HouseStyle' 'OverallQual' 'OverallCond'
 'YearBuilt' 'YearRemodAdd' 'RoofStyle' 'RoofMatl' 'Exterior1st'
 'Exterior2nd' 'MasVnrType' 'MasVnrArea' 'ExterQual' 'ExterCond'
 'Foundation' 'BsmtQual' 'BsmtCond' 'BsmtExposure' 'BsmtFinType1'
 'BsmtFinSF1' 'BsmtFinType2' 'BsmtFinSF2' 'BsmtUnfSF' 'TotalBsmtSF'
 'Heating' 'HeatingQC' 'CentralAir' 'Electrical' '1stFlrSF' '2ndFlrSF'
 'LowQualFinSF' 'GrLivArea' 'BsmtFullBath' 'BsmtHalfBath' 'FullBath'
 'HalfBath' 'BedroomAbvGr' 'KitchenAbvGr' 'KitchenQual' 'TotRmsAbvGrd'
 'Functional' 'Fireplaces' 'GarageType' 'GarageYrBlt' 'GarageFinish'
 'GarageCars' 'GarageArea' 'GarageQual' 'GarageCond' 'PavedDrive'
 'WoodDeckSF' 'OpenPorchSF' 'EnclosedPorch' '3SsnPorch' 'ScreenPorch'
 'PoolArea' 'MiscVal' 'MoSold' 'YrSold' 'SaleType' 'SaleCondition'
 'SalePrice']

### Ожидаемый результат:

```
['Id' 'MSSubClass' 'MSZoning' 'LotArea' 'Street' 'LotShape' 'LandContour'
 'Utilities' 'LotConfig' 'LandSlope' 'Neighborhood' 'Condition1'
 'Condition2' 'BldgType' 'HouseStyle' 'OverallQual' 'OverallCond'
 'YearBuilt' 'YearRemodAdd' 'RoofStyle' 'RoofMatl' 'Exterior1st'
 'Exterior2nd' 'MasVnrType' 'MasVnrArea' 'ExterQual' 'ExterCond'
 'Foundation' 'BsmtQual' 'BsmtCond' 'BsmtExposure' 'BsmtFinType1'
 'BsmtFinSF1' 'BsmtFinType2' 'BsmtFinSF2' 'BsmtUnfSF' 'TotalBsmtSF'
 'Heating' 'HeatingQC' 'CentralAir' 'Electrical' '1stFlrSF' '2ndFlrSF'
 'LowQualFinSF' 'GrLivArea' 'BsmtFullBath' 'BsmtHalfBath' 'FullBath'
 'HalfBath' 'BedroomAbvGr' 'KitchenAbvGr' 'KitchenQual' 'TotRmsAbvGrd'
 'Functional' 'Fireplaces' 'GarageType' 'GarageYrBlt' 'GarageFinish'
 'GarageCars' 'GarageArea' 'GarageQual' 'GarageCond' 'PavedDrive'
 'WoodDeckSF' 'OpenPorchSF' 'EnclosedPorch' '3SsnPorch' 'ScreenPorch'
 'PoolArea' 'MiscVal' 'MoSold' 'YrSold' 'SaleType' 'SaleCondition'
 'SalePrice']
```

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 75 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1338 non-null   int64
 1   MSSubClass     1338 non-null   int64
 2   MSZoning       1338 non-null   object
 3   LotArea        1338 non-null   int64
 4   Street         1338 non-null   object
 5   LotShape       1338 non-null   object
 6   LandContour    1338 non-null   object
 7   Utilities      1338 non-null   object
 8   LotConfig      1338 non-null   object
 9   LandSlope      1338 non-null   object
 10  Neighborhood   1338 non-null   object
 11  Condition1     1338 non-null   object
 12  Condition2     1338 non-null   object
 13  BldgType       1338 non-null   object
 14  HouseStyle     1338 non-null   object
 15  OverallQual    1338 non-null   int64
 16  OverallCond    1338 non-null   int64
 17  YearBuilt      1338 non-null   int64
 18  YearRemodAdd   1338 non-null   int64
 19  RoofStyle      1338 non-null   object
 20  RoofMatl       1338 non-null   object
 21  Exterior1st    1338 non-null   object
 22  Exterior2nd    1338 non-null   object
 23  MasVnrType     1338 non-null   object
 24  MasVnrArea     1338 non-null   float64
 25  ExterQual      1338 non-null   object
 26  ExterCond      1338 non-null   object
 27  Foundation     1338 non-null   object
 28  BsmtQual       1338 non-null   object
 29  BsmtCond       1338 non-null   object
 30  BsmtExposure   1338 non-null   object
 31  BsmtFinType1   1338 non-null   object
 32  BsmtFinSF1     1338 non-null   int64
 33  BsmtFinType2   1338 non-null   object
 34  BsmtFinSF2     1338 non-null   int64
 35  BsmtUnfSF      1338 non-null   int64
 36  TotalBsmtSF    1338 non-null   int64
 37  Heating        1338 non-null   object
 38  HeatingQC      1338 non-null   object
 39  CentralAir     1338 non-null   object
 40  Electrical     1338 non-null   object
 41  1stFlrSF       1338 non-null   int64
 42  2ndFlrSF       1338 non-null   int64
 43  LowQualFinSF   1338 non-null   int64
 44  GrLivArea      1338 non-null   int64
 45  BsmtFullBath   1338 non-null   int64
 46  BsmtHalfBath   1338 non-null   int64
 47  FullBath       1338 non-null   int64
 48  HalfBath       1338 non-null   int64
 49  BedroomAbvGr   1338 non-null   int64
 50  KitchenAbvGr   1338 non-null   int64
 51  KitchenQual    1338 non-null   object
 52  TotRmsAbvGrd   1338 non-null   int64
 53  Functional     1338 non-null   object
 54  Fireplaces     1338 non-null   int64
 55  GarageType     1338 non-null   object
 56  GarageYrBlt    1338 non-null   float64
 57  GarageFinish   1338 non-null   object
 58  GarageCars     1338 non-null   int64
 59  GarageArea     1338 non-null   int64
 60  GarageQual     1338 non-null   object
 61  GarageCond     1338 non-null   object
 62  PavedDrive     1338 non-null   object
 63  WoodDeckSF     1338 non-null   int64
 64  OpenPorchSF    1338 non-null   int64
 65  EnclosedPorch  1338 non-null   int64
 66  3SsnPorch      1338 non-null   int64
 67  ScreenPorch    1338 non-null   int64
 68  PoolArea       1338 non-null   int64
 69  MiscVal        1338 non-null   int64
 70  MoSold         1338 non-null   int64
 71  YrSold         1338 non-null   int64
 72  SaleType       1338 non-null   object
 73  SaleCondition  1338 non-null   object
 74  SalePrice      1338 non-null   int64
dtypes: float64(2), int64(35), object(38)
memory usage: 784.1+ KB

### Ожидаемый результат:

```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 75 columns):
Id               1338 non-null int64
MSSubClass       1338 non-null int64
MSZoning         1338 non-null object
LotArea          1338 non-null int64
Street           1338 non-null object
LotShape         1338 non-null object
LandContour      1338 non-null object
Utilities        1338 non-null object
LotConfig        1338 non-null object
LandSlope        1338 non-null object
Neighborhood     1338 non-null object
Condition1       1338 non-null object
Condition2       1338 non-null object
BldgType         1338 non-null object
HouseStyle       1338 non-null object
OverallQual      1338 non-null int64
OverallCond      1338 non-null int64
YearBuilt        1338 non-null int64
YearRemodAdd     1338 non-null int64
RoofStyle        1338 non-null object
RoofMatl         1338 non-null object
Exterior1st      1338 non-null object
Exterior2nd      1338 non-null object
MasVnrType       1338 non-null object
MasVnrArea       1338 non-null float64
ExterQual        1338 non-null object
ExterCond        1338 non-null object
Foundation       1338 non-null object
BsmtQual         1338 non-null object
BsmtCond         1338 non-null object
BsmtExposure     1338 non-null object
BsmtFinType1     1338 non-null object
BsmtFinSF1       1338 non-null int64
BsmtFinType2     1338 non-null object
BsmtFinSF2       1338 non-null int64
BsmtUnfSF        1338 non-null int64
TotalBsmtSF      1338 non-null int64
Heating          1338 non-null object
HeatingQC        1338 non-null object
CentralAir       1338 non-null object
Electrical       1338 non-null object
1stFlrSF         1338 non-null int64
2ndFlrSF         1338 non-null int64
LowQualFinSF     1338 non-null int64
GrLivArea        1338 non-null int64
BsmtFullBath     1338 non-null int64
BsmtHalfBath     1338 non-null int64
FullBath         1338 non-null int64
HalfBath         1338 non-null int64
BedroomAbvGr     1338 non-null int64
KitchenAbvGr     1338 non-null int64
KitchenQual      1338 non-null object
TotRmsAbvGrd     1338 non-null int64
Functional       1338 non-null object
Fireplaces       1338 non-null int64
GarageType       1338 non-null object
GarageYrBlt      1338 non-null float64
GarageFinish     1338 non-null object
GarageCars       1338 non-null int64
GarageArea       1338 non-null int64
GarageQual       1338 non-null object
GarageCond       1338 non-null object
PavedDrive       1338 non-null object
WoodDeckSF       1338 non-null int64
OpenPorchSF      1338 non-null int64
EnclosedPorch    1338 non-null int64
3SsnPorch        1338 non-null int64
ScreenPorch      1338 non-null int64
PoolArea         1338 non-null int64
MiscVal          1338 non-null int64
MoSold           1338 non-null int64
YrSold           1338 non-null int64
SaleType         1338 non-null object
SaleCondition    1338 non-null object
SalePrice        1338 non-null int64
dtypes: float64(2), int64(35), object(38)
memory usage: 784.1+ KB
```

In [30]:
print(data.describe())

                Id   MSSubClass  ...       YrSold      SalePrice
count  1338.000000  1338.000000  ...  1338.000000    1338.000000
mean    731.228700    56.136024  ...  2007.805680  186761.782511
std     421.779691    41.252576  ...     1.330691   78913.847668
min       1.000000    20.000000  ...  2006.000000   35311.000000
25%     366.250000    20.000000  ...  2007.000000  135000.000000
50%     730.500000    50.000000  ...  2008.000000  168500.000000
75%    1098.750000    70.000000  ...  2009.000000  220000.000000
max    1460.000000   190.000000  ...  2010.000000  755000.000000

[8 rows x 37 columns]

### Ожидаемый результат:

```
                Id   MSSubClass        LotArea  OverallQual  OverallCond  \
count  1338.000000  1338.000000    1338.000000  1338.000000  1338.000000   
mean    731.228700    56.136024   10706.294469     6.219731     5.596413   
std     421.779691    41.252576   10336.621126     1.324472     1.078124   
min       1.000000    20.000000    1300.000000     2.000000     2.000000   
25%     366.250000    20.000000    7744.000000     5.000000     5.000000   
50%     730.500000    50.000000    9600.000000     6.000000     5.000000   
75%    1098.750000    70.000000   11760.750000     7.000000     6.000000   
max    1460.000000   190.000000  215245.000000    10.000000     9.000000   

         YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1   BsmtFinSF2  ...  \
count  1338.000000   1338.000000  1338.000000  1338.000000  1338.000000  ...   
mean   1973.029148   1985.668909   110.360239   464.234679    49.218236  ...   
std      29.563540     20.296463   185.604816   458.792420   166.196584  ...   
min    1880.000000   1950.000000     0.000000     0.000000     0.000000  ...   
25%    1956.000000   1968.000000     0.000000     0.000000     0.000000  ...   
50%    1976.000000   1994.500000     0.000000   413.000000     0.000000  ...   
75%    2001.000000   2004.000000   174.000000   733.000000     0.000000  ...   
max    2010.000000   2010.000000  1600.000000  5644.000000  1474.000000  ...   

        WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch  \
count  1338.000000  1338.000000    1338.000000  1338.000000   1338.00000   
mean     99.384903    47.782511      21.263827     3.585949     16.43423   
std     127.537065    65.362562      60.843964    30.224622     58.05159   
min       0.000000     0.000000       0.000000     0.000000      0.00000   
25%       0.000000     0.000000       0.000000     0.000000      0.00000   
50%       6.000000    28.000000       0.000000     0.000000      0.00000   
75%     174.500000    70.000000       0.000000     0.000000      0.00000   
max     857.000000   547.000000     552.000000   508.000000    480.00000   

          PoolArea       MiscVal       MoSold       YrSold      SalePrice  
count  1338.000000   1338.000000  1338.000000  1338.000000    1338.000000  
mean      3.010463     42.932735     6.331839  2007.805680  186761.782511  
std      41.961337    508.056255     2.699437     1.330691   78913.847668  
min       0.000000      0.000000     1.000000  2006.000000   35311.000000  
25%       0.000000      0.000000     5.000000  2007.000000  135000.000000  
50%       0.000000      0.000000     6.000000  2008.000000  168500.000000  
75%       0.000000      0.000000     8.000000  2009.000000  220000.000000  
max     738.000000  15500.000000    12.000000  2010.000000  755000.000000  

[8 rows x 37 columns]
```

**Распечатайте первые и последние 5 строк pandas.DataFrame:**

In [31]:
#Начало вашего кода
print(data.head())
print(data.tail())
#Конец вашего кода

   Id  MSSubClass MSZoning  LotArea  ... YrSold SaleType SaleCondition SalePrice
0   1          60       RL     8450  ...   2008       WD        Normal    208500
1   2          20       RL     9600  ...   2007       WD        Normal    181500
2   3          60       RL    11250  ...   2008       WD        Normal    223500
3   4          70       RL     9550  ...   2006       WD       Abnorml    140000
4   5          60       RL    14260  ...   2008       WD        Normal    250000

[5 rows x 75 columns]
        Id  MSSubClass MSZoning  ...  SaleType SaleCondition SalePrice
1333  1456          60       RL  ...        WD        Normal    175000
1334  1457          20       RL  ...        WD        Normal    210000
1335  1458          70       RL  ...        WD        Normal    266500
1336  1459          20       RL  ...        WD        Normal    142125
1337  1460          20       RL  ...        WD        Normal    147500

[5 rows x 75 columns]

### Ожидаемый результат:

```
   Id  MSSubClass MSZoning  LotArea Street LotShape LandContour Utilities  \
0   1          60       RL     8450   Pave      Reg         Lvl    AllPub   
1   2          20       RL     9600   Pave      Reg         Lvl    AllPub   
2   3          60       RL    11250   Pave      IR1         Lvl    AllPub   
3   4          70       RL     9550   Pave      IR1         Lvl    AllPub   
4   5          60       RL    14260   Pave      IR1         Lvl    AllPub   

  LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch PoolArea  \
0    Inside       Gtl  ...             0         0           0        0   
1       FR2       Gtl  ...             0         0           0        0   
2    Inside       Gtl  ...             0         0           0        0   
3    Corner       Gtl  ...           272         0           0        0   
4       FR2       Gtl  ...             0         0           0        0   

  MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0       0       2    2008        WD         Normal    208500  
1       0       5    2007        WD         Normal    181500  
2       0       9    2008        WD         Normal    223500  
3       0       2    2006        WD        Abnorml    140000  
4       0      12    2008        WD         Normal    250000  

[5 rows x 75 columns]
        Id  MSSubClass MSZoning  LotArea Street LotShape LandContour  \
1333  1456          60       RL     7917   Pave      Reg         Lvl   
1334  1457          20       RL    13175   Pave      Reg         Lvl   
1335  1458          70       RL     9042   Pave      Reg         Lvl   
1336  1459          20       RL     9717   Pave      Reg         Lvl   
1337  1460          20       RL     9937   Pave      Reg         Lvl   

     Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
1333    AllPub    Inside       Gtl  ...             0         0           0   
1334    AllPub    Inside       Gtl  ...             0         0           0   
1335    AllPub    Inside       Gtl  ...             0         0           0   
1336    AllPub    Inside       Gtl  ...           112         0           0   
1337    AllPub    Inside       Gtl  ...             0         0           0   

     PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
1333        0       0       8    2007        WD         Normal    175000  
1334        0       0       2    2010        WD         Normal    210000  
1335        0    2500       5    2010        WD         Normal    266500  
1336        0       0       4    2010        WD         Normal    142125  
1337        0       0       6    2008        WD         Normal    147500  

[5 rows x 75 columns]
```

### Шаг 2

Запустите приведенный ниже блок кода и попытайтесь получить представление о данных, которые вы просматриваете.

In [32]:
pd_data=data.copy()
pd_data.set_index("Id",inplace=True)
pd_data

      MSSubClass MSZoning  LotArea  ... SaleType SaleCondition SalePrice
Id                                  ...
1             60       RL     8450  ...       WD        Normal    208500
2             20       RL     9600  ...       WD        Normal    181500
3             60       RL    11250  ...       WD        Normal    223500
4             70       RL     9550  ...       WD       Abnorml    140000
5             60       RL    14260  ...       WD        Normal    250000
...          ...      ...      ...  ...      ...           ...       ...
1456          60       RL     7917  ...       WD        Normal    175000
1457          20       RL    13175  ...       WD        Normal    210000
1458          70       RL     9042  ...       WD        Normal    266500
1459          20       RL     9717  ...       WD        Normal    142125
1460          20       RL     9937  ...       WD        Normal    147500

[1338 rows x 74 columns]

In [33]:
pd_data.dtypes

MSSubClass        int64
MSZoning         object
LotArea           int64
Street           object
LotShape         object
                  ...
MoSold            int64
YrSold            int64
SaleType         object
SaleCondition    object
SalePrice         int64
Length: 74, dtype: object

In [34]:
#data.columns.to_list()
str_list = []
num_list = []
for column in pd_data.columns:
  if type(pd_data[column][1])==str:
    str_list.append(column)
  elif type(pd_data[column][1])!=str and not None:
    num_list.append(column)
print(pd_data[str_list])
print(pd_data[num_list])

     MSZoning Street LotShape  ... PavedDrive SaleType SaleCondition
Id                             ...
1          RL   Pave      Reg  ...          Y       WD        Normal
2          RL   Pave      Reg  ...          Y       WD        Normal
3          RL   Pave      IR1  ...          Y       WD        Normal
4          RL   Pave      IR1  ...          Y       WD       Abnorml
5          RL   Pave      IR1  ...          Y       WD        Normal
...       ...    ...      ...  ...        ...      ...           ...
1456       RL   Pave      Reg  ...          Y       WD        Normal
1457       RL   Pave      Reg  ...          Y       WD        Normal
1458       RL   Pave      Reg  ...          Y       WD        Normal
1459       RL   Pave      Reg  ...          Y       WD        Normal
1460       RL   Pave      Reg  ...          Y       WD        Normal

[1338 rows x 38 columns]
      MSSubClass  LotArea  OverallQual  ...  MoSold  YrSold  SalePrice
Id                                      ...
1             60     8450            7  ...       2    2008     208500
2             20     9600            6  ...       5    2007     181500
3             60    11250            7  ...       9    2008     223500
4             70     9550            7  ...       2    2006     140000
5             60    14260            8  ...      12    2008     250000
...          ...      ...          ...  ...     ...     ...        ...
1456          60     7917            6  ...       8    2007     175000
1457          20    13175            6  ...       2    2010     210000
1458          70     9042            7  ...       5    2010     266500
1459          20     9717            5  ...       4    2010     142125
1460          20     9937            5  ...       6    2008     147500

[1338 rows x 36 columns]

Пожалуйста, реализуйте функцию ```split_str nums(date)```, которая возвращает один ```DataFrame```, содержащий **не числовые** элементы, и второй ```DataFrame``` **только с числовыми** элементами.

In [35]:
#Начало вашего кода
def split_str_nums(data):
  str_list = []
  num_list = []
  row = data.index[0]
  for column in data.columns:
    if type(data[column][row])==str:
      str_list.append(column)
    elif type(data[column][row])!=str and not None:
      num_list.append(column)
  return data[str_list], data[num_list]
#Конец вашего кода
str_data,num_data=split_str_nums(pd_data)

In [36]:
print(str_data)

     MSZoning Street LotShape  ... PavedDrive SaleType SaleCondition
Id                             ...
1          RL   Pave      Reg  ...          Y       WD        Normal
2          RL   Pave      Reg  ...          Y       WD        Normal
3          RL   Pave      IR1  ...          Y       WD        Normal
4          RL   Pave      IR1  ...          Y       WD       Abnorml
5          RL   Pave      IR1  ...          Y       WD        Normal
...       ...    ...      ...  ...        ...      ...           ...
1456       RL   Pave      Reg  ...          Y       WD        Normal
1457       RL   Pave      Reg  ...          Y       WD        Normal
1458       RL   Pave      Reg  ...          Y       WD        Normal
1459       RL   Pave      Reg  ...          Y       WD        Normal
1460       RL   Pave      Reg  ...          Y       WD        Normal

[1338 rows x 38 columns]

### Ожидаемый результат:

```
     MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
Id                                                                        
1          RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
2          RL   Pave      Reg         Lvl    AllPub       FR2       Gtl   
3          RL   Pave      IR1         Lvl    AllPub    Inside       Gtl   
4          RL   Pave      IR1         Lvl    AllPub    Corner       Gtl   
5          RL   Pave      IR1         Lvl    AllPub       FR2       Gtl   
...       ...    ...      ...         ...       ...       ...       ...   
1456       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1457       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1458       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1459       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1460       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   

     Neighborhood Condition1 Condition2  ... Electrical KitchenQual  \
Id                                       ...                          
1         CollgCr       Norm       Norm  ...      SBrkr          Gd   
2         Veenker      Feedr       Norm  ...      SBrkr          TA   
3         CollgCr       Norm       Norm  ...      SBrkr          Gd   
4         Crawfor       Norm       Norm  ...      SBrkr          Gd   
5         NoRidge       Norm       Norm  ...      SBrkr          Gd   
...           ...        ...        ...  ...        ...         ...   
1456      Gilbert       Norm       Norm  ...      SBrkr          TA   
1457       NWAmes       Norm       Norm  ...      SBrkr          TA   
1458      Crawfor       Norm       Norm  ...      SBrkr          Gd   
1459        NAmes       Norm       Norm  ...      FuseA          Gd   
1460      Edwards       Norm       Norm  ...      SBrkr          TA   

     Functional GarageType GarageFinish GarageQual GarageCond PavedDrive  \
Id                                                                         
1           Typ     Attchd          RFn         TA         TA          Y   
2           Typ     Attchd          RFn         TA         TA          Y   
3           Typ     Attchd          RFn         TA         TA          Y   
4           Typ     Detchd          Unf         TA         TA          Y   
5           Typ     Attchd          RFn         TA         TA          Y   
...         ...        ...          ...        ...        ...        ...   
1456        Typ     Attchd          RFn         TA         TA          Y   
1457       Min1     Attchd          Unf         TA         TA          Y   
1458        Typ     Attchd          RFn         TA         TA          Y   
1459        Typ     Attchd          Unf         TA         TA          Y   
1460        Typ     Attchd          Fin         TA         TA          Y   

     SaleType SaleCondition  
Id                           
1          WD        Normal  
2          WD        Normal  
3          WD        Normal  
4          WD       Abnorml  
5          WD        Normal  
...       ...           ...  
1456       WD        Normal  
1457       WD        Normal  
1458       WD        Normal  
1459       WD        Normal  
1460       WD        Normal  

[1338 rows x 38 columns]
```

In [37]:
print(num_data)

      MSSubClass  LotArea  OverallQual  ...  MoSold  YrSold  SalePrice
Id                                      ...
1             60     8450            7  ...       2    2008     208500
2             20     9600            6  ...       5    2007     181500
3             60    11250            7  ...       9    2008     223500
4             70     9550            7  ...       2    2006     140000
5             60    14260            8  ...      12    2008     250000
...          ...      ...          ...  ...     ...     ...        ...
1456          60     7917            6  ...       8    2007     175000
1457          20    13175            6  ...       2    2010     210000
1458          70     9042            7  ...       5    2010     266500
1459          20     9717            5  ...       4    2010     142125
1460          20     9937            5  ...       6    2008     147500

[1338 rows x 36 columns]

### Ожидаемый результат:

```
      MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  YearRemodAdd  \
Id                                                                             
1             60     8450            7            5       2003          2003   
2             20     9600            6            8       1976          1976   
3             60    11250            7            5       2001          2002   
4             70     9550            7            5       1915          1970   
5             60    14260            8            5       2000          2000   
...          ...      ...          ...          ...        ...           ...   
1456          60     7917            6            5       1999          2000   
1457          20    13175            6            6       1978          1988   
1458          70     9042            7            9       1941          2006   
1459          20     9717            5            6       1950          1996   
1460          20     9937            5            6       1965          1965   

      MasVnrArea  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  ...  WoodDeckSF  \
Id                                                   ...               
1          196.0         706           0        150  ...           0   
2            0.0         978           0        284  ...         298   
3          162.0         486           0        434  ...           0   
4            0.0         216           0        540  ...           0   
5          350.0         655           0        490  ...         192   
...          ...         ...         ...        ...  ...         ...   
1456         0.0           0           0        953  ...           0   
1457       119.0         790         163        589  ...         349   
1458         0.0         275           0        877  ...           0   
1459         0.0          49        1029          0  ...         366   
1460         0.0         830         290        136  ...         736   

      OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea  MiscVal  \
Id                                                                            
1              61              0          0            0         0        0   
2               0              0          0            0         0        0   
3              42              0          0            0         0        0   
4              35            272          0            0         0        0   
5              84              0          0            0         0        0   
...           ...            ...        ...          ...       ...      ...   
1456           40              0          0            0         0        0   
1457            0              0          0            0         0        0   
1458           60              0          0            0         0     2500   
1459            0            112          0            0         0        0   
1460           68              0          0            0         0        0   

      MoSold  YrSold  SalePrice  
Id                               
1          2    2008     208500  
2          5    2007     181500  
3          9    2008     223500  
4          2    2006     140000  
5         12    2008     250000  
...      ...     ...        ...  
1456       8    2007     175000  
1457       2    2010     210000  
1458       5    2010     266500  
1459       4    2010     142125  
1460       6    2008     147500  

[1338 rows x 36 columns]
```

### Шаг 3

Как видно из данных, в некоторых столбцах много повторений. Пожалуйста, реализуйте функцию ```count_values(data, column)```, которая будет подсчитывать количество повторений для определенного столбца во входном аргументе ```data```.

Эта функция должна обрабатывать следующие случаи:
* если входной аргумент ```data``` пуст, выведите ошибку и верните пустой ```DataFrame```.
* если входной аргумент ```column``` имеет тип ```str```, верните ```DataFrame``` с результатами подсчета повторных значений для данного столбца во входном аргументе `` `data```.
* если входной аргумент ```column``` имеет тип ```list```, верните ```DataFrame``` с количеством повторных значений результатов для указанных столбцов из входного аргумента ```data```.
* если входной аргумент ```column``` пуст, верните ```DataFrame``` с количеством повторных значений результатов для всех столбцов из входного аргумента ```data```.


```DataFrame```, возвращаемый функцией, должен быть отсортирован в порядке убывания.

In [38]:
print(data['MSSubClass'].dtypes)
print(str(data['MSSubClass'].dtypes) == "int64")
print(str_data["MSZoning"])

int64
True
Id
1       RL
2       RL
3       RL
4       RL
5       RL
        ..
1456    RL
1457    RL
1458    RL
1459    RL
1460    RL
Name: MSZoning, Length: 1338, dtype: object

In [41]:
def count_values(data=None, column=None):
  if type(data)==type(pd.DataFrame()):
    typ=float
    if type(column)==type(str()):
      column=[column]
      typ=int
    elif column==None:
      column=data.columns.to_list()
    data_first=pd.DataFrame({'frequency':{}})
    for col in column:
      data_finally=data[col].value_counts().sort_values(ascending=False)
      for i,j in data_finally.items():
        row=pd.Series(data={'frequency':j}, name=i)
        data_first=data_first.append(row, ignore_index=False)
    return data_first.astype(typ)
  elif data==None:
    print('Error: Data is None')
    return pd.DataFrame({})

In [42]:
print(count_values(data=str_data))

         frequency
RL          1066.0
RM           191.0
FV            62.0
RH            11.0
C (all)        8.0
...            ...
Partial      120.0
Abnorml       86.0
Family        20.0
Alloca         7.0
AdjLand        1.0

[229 rows x 1 columns]

### Ожидаемый результат:

```
         frequency
RL          1066.0
RM           191.0
FV            62.0
RH            11.0
C (all)        8.0
...            ...
Partial      120.0
Abnorml       86.0
Family        20.0
Alloca         7.0
AdjLand        1.0

[229 rows x 1 columns]
```

In [43]:
print(count_values(data=str_data,column="Condition1"))

        frequency
Norm         1162
Feedr          63
Artery         43
RRAn           26
PosN           19
RRAe           10
PosA            8
RRNn            5
RRNe            2

### Ожидаемый результат:

```
        frequency
Norm         1162
Feedr          63
Artery         43
RRAn           26
PosN           19
RRAe           10
PosA            8
RRNn            5
RRNe            2
```

In [44]:
print(count_values(data=str_data,column=["Condition1","Condition2"]))

        frequency
Norm       1162.0
Feedr        63.0
Artery       43.0
RRAn         26.0
PosN         19.0
RRAe         10.0
PosA          8.0
RRNn          5.0
RRNe          2.0
Norm       1324.0
Feedr         5.0
PosN          2.0
Artery        2.0
RRNn          2.0
RRAe          1.0
PosA          1.0
RRAn          1.0

### Ожидаемый результат:

```
        frequency
Norm       1162.0
Feedr        63.0
Artery       43.0
RRAn         26.0
PosN         19.0
RRAe         10.0
PosA          8.0
RRNn          5.0
RRNe          2.0
Norm       1324.0
Feedr         5.0
Artery        2.0
PosN          2.0
RRNn          2.0
RRAn          1.0
RRAe          1.0
PosA          1.0
```

### Шаг 4

Пожалуйста, реализуйте функцию ```save_to_csv(имя файла, данные)```, которая будет экспортировать **непустой** ```DataFrame``` в csv-файл ```filename```. Обратите внимание на обработку ошибок входных аргументов.

In [45]:
#Начало вашего кода
def save_to_csv(filename, data=pd.DataFrame()):
  if data is not None:
    if os.path.isfile(filename+'.csv'):
      print('Error: House_Prices.csv already exists, please try another file name')
    else:
      data.to_csv(filename+'.csv')
      print('{}.csv is created'.format(filename))
#Конец вашего кода

In [46]:
save_to_csv("House_Prices",str_data)

House_Prices.csv is created

### Ожидаемый результат:

```
'Error: House_Prices.csv already exists, please try another file name'
```

In [47]:
save_to_csv("str_house_prices",str_data)

str_house_prices.csv is created

### Ожидаемый результат:

```
'str_house_prices.csv is created'
```

In [48]:
save_to_csv("num_house_prices",num_data)

num_house_prices.csv is created

### Ожидаемый результат:

```
'num_house_prices.csv is created'
```

In [49]:
os.path.exists("num_house_prices.csv")

True

### Ожидаемый результат:

```
True
```

# Прекрасная работа!